"""
Lambda: create_github_pr
Clones website repo, adds blog post file, and creates a GitHub pull request.
"""
import sys, os
sys.path.insert(0, "/opt/python")
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import json
import base64
import urllib.request
import urllib.error
from datetime import datetime, timezone
from shared.supabase_client import get_client
from shared.utils import get_ssm, now_iso, read_json_from_s3

GITHUB_API = "https://api.github.com"


def gh_request(method: str, path: str, token: str, body=None) -> dict:
    url  = f"{GITHUB_API}{path}"
    data = json.dumps(body).encode() if body else None
    req  = urllib.request.Request(
        url, data=data,
        headers={
            "Authorization":        f"Bearer {token}",
            "Accept":               "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type":         "application/json",
            "User-Agent":           "StellarWorkflows/1.0",
        },
        method=method,
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"GitHub {method} {path}: {e.code} {e.read().decode()}")


def handler(event, context):
    blog   = event["blog"]
    blog_id = event["blogId"]
    if blog.get("content_s3_key"):
        blog = {**blog, **read_json_from_s3(blog["content_s3_key"])}

    token      = get_ssm(os.environ["GITHUB_TOKEN_PARAM"])
    repo_owner = os.environ["WEBSITE_REPO_OWNER"]
    repo_name  = os.environ["WEBSITE_REPO_NAME"]
    base_branch = os.environ.get("WEBSITE_BASE_BRANCH", "main")
    blog_dir    = os.environ.get("WEBSITE_BLOG_DIR", "content/blog")

    # 1. Get base branch SHA
    ref_data    = gh_request("GET", f"/repos/{repo_owner}/{repo_name}/git/ref/heads/{base_branch}", token)
    base_sha    = ref_data["object"]["sha"]

    # 2. Create a new branch
    today      = datetime.now(timezone.utc).strftime("%Y%m%d")
    new_branch = f"blog/{blog['slug'][:40]}-{today}"
    gh_request("POST", f"/repos/{repo_owner}/{repo_name}/git/refs", token, {
        "ref": f"refs/heads/{new_branch}",
        "sha": base_sha,
    })

    # 3. Build blog file content (MDX / Markdown with frontmatter)
    pub_date   = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    tags_yaml  = "\n  - ".join(blog.get("tags", ["general"]))
    file_content = f"""---
title: "{blog['title']}"
date: "{pub_date}"
excerpt: "{blog.get('excerpt', '')}"
image: "{blog.get('image_url', '')}"
author: "{blog.get('author', 'Stellar Global Supplies')}"
tags:
  - {tags_yaml}
---

{blog['content']}
"""

    # 4. Create file in new branch
    file_path = f"{blog_dir}/{blog['slug']}.md"
    encoded   = base64.b64encode(file_content.encode()).decode()
    gh_request("PUT", f"/repos/{repo_owner}/{repo_name}/contents/{file_path}", token, {
        "message": f"feat: add blog post '{blog['title']}'",
        "content": encoded,
        "branch":  new_branch,
    })

    # 5. Open Pull Request
    pr = gh_request("POST", f"/repos/{repo_owner}/{repo_name}/pulls", token, {
        "title": f"[Blog] {blog['title']}",
        "body":  (
            f"## New Blog Post\n\n"
            f"**Title:** {blog['title']}\n\n"
            f"**Excerpt:** {blog.get('excerpt', '')}\n\n"
            f"**Tags:** {', '.join(blog.get('tags', []))}\n\n"
            f"**Featured Image:** {blog.get('image_url', '')}\n\n"
            f"---\n*Auto-generated by Stellar Workflows Platform*"
        ),
        "head": new_branch,
        "base": base_branch,
    })

    pr_url    = pr["html_url"]
    pr_number = pr["number"]

    # Update Supabase
    db = get_client()
    db.update("blog_posts", {
        "status":    "pr_created",
        "pr_url":    pr_url,
        "pr_number": pr_number,
    }, params=f"id=eq.{blog_id}")

    return {
        **event,
        "prUrl":    pr_url,
        "prNumber": pr_number,
        "branch":   new_branch,
    }
